name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]


jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: contains(COMMIT_MESSAGES, 'try')
        run: echo "$COMMIT_MESSAGES"
      # should run
      - if: contains(${{ github.event.commits.*.message }}, "test")
        name: test contains test
        run: |
          echo "test"
          echo "${{ toJson(github.event.commits.*.message) }}"
          echo "${{ github.event.commits.*.message }}"
      # should not run
      - if: contains(${{ github.event.commits.*.message }}, "hmtk5")
        name: test contains hmtk5
        run: |
          echo "hmtk5"
          echo "${{ github.event.commits.*.message }}"
          echo "${{ github.event.commits.*.message }}"
